# Generated by Django 3.0.3 on 2020-04-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takanon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('takanon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takanon.Takanon')),
            ],
        ),
    ]
