# Generated by Django 3.0.3 on 2020-04-21 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('speech', models.TextField()),
                ('parliament_member_speech', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
